### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by drgndomdev** [drgndomdev/quickdashboard#2]
In commit 3ef465b7f70234be31e997b751e1b64800177b46, building the project fails due to main() function in pyGraphs.cpp

The same name is used for the function in main.cpp, is it the name of the function causing the error or the name of the file?

**Comment by drgndomdev** [comment]
@Twon

**Comment by Twon** [comment]
Hey, I've pulled the latest and it's building for me so I can't recreate the exact problem.  But in general a translation unit (a *.cpp file) any symbol must adhere to the ODR (one definition rule).  That applies to all symbols (variables, namespaces, classes, functions). Is there are 2 translation units with a main() function defined in then when the link tries to pull them together into an executable then there will be an ODR violation here because the symbol is now defined in multiple places.  There should be only one main() should be defined.

But if you add more details I can try an recreate locally...
